sudo: false
language: python
services:
  - memcached
python:
  - "2.7"
install:
  - pip install -r restclients/requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
script:
  - pep8 --exclude=migrations,restclients/sws/,restclients/canvas/,restclients/uwnetid/,restclients/test/,restclients/signals/,restclients/hfs/,restclients/r25,restclients/nws.py,restclients/sms.py,restclients/library/ restclients/
  - python -m compileall restclients/
  - coverage run --source=restclients manage.py test restclients
after_script:
  - coveralls
