sudo: false
language: python
services:
  - memcached
python:
  - "2.7"
  - "2.6"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6* ]]; then pip install -r travis-ci/python-2.6-require-django-1.6.txt; fi
  - pip install -r restclients/requirements.txt
env:
  - DJANGO_VERSION='<1.8'
  - DJANGO_VERSION='>1.9'
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6* ]]; then pip install -U "Django$DJANGO_VERSION"; fi
  - cp travis-ci/manage.py manage.py
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6* ]]; then python manage.py migrate --noinput; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6* ]]; then python manage.py syncdb --noinput; fi
script:
  - pep8 --exclude=migrations,restclients/sws/,restclients/canvas/,restclients/uwnetid/,restclients/test/,restclients/signals/,restclients/hfs/,restclients/r25,restclients/nws.py,restclients/sms.py,restclients/library/ restclients/
  - python -m compileall restclients/
  - coverage run --source=restclients manage.py test restclients
after_script:
  - coveralls
